#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

PROJECT_ID="${PROJECT_ID:-predicta-a4758}"
REGION="${REGION:-asia-south1}"
SERVICE_NAME="${SERVICE_NAME:-predicta-backend}"
ALLOWED_ORIGINS="${PREDICTA_ALLOWED_ORIGINS:-https://predicta.rudraix.com,https://predicta.bhaumikmehta.com,https://predicta-a4758.web.app}"
BOOTSTRAP_ADMINS="${PREDICTA_BOOTSTRAP_ADMIN_EMAILS:-}"
CLOUD_RUN_INGRESS="${CLOUD_RUN_INGRESS:-all}"
CLOUD_RUN_MAX_INSTANCES="${CLOUD_RUN_MAX_INSTANCES:-3}"
CLOUD_RUN_CONCURRENCY="${CLOUD_RUN_CONCURRENCY:-40}"

ENV_VARS=(
  "PREDICTA_ALLOWED_ORIGINS=$ALLOWED_ORIGINS"
  "PREDICTA_BOOTSTRAP_ADMIN_EMAILS=$BOOTSTRAP_ADMINS"
  "PREDICTA_RATE_LIMIT_ENABLED=${PREDICTA_RATE_LIMIT_ENABLED:-true}"
  "PREDICTA_RATE_LIMIT_KUNDLI_PER_MINUTE=${PREDICTA_RATE_LIMIT_KUNDLI_PER_MINUTE:-12}"
  "PREDICTA_RATE_LIMIT_KUNDLI_PER_HOUR=${PREDICTA_RATE_LIMIT_KUNDLI_PER_HOUR:-120}"
  "PREDICTA_RATE_LIMIT_PASS_REDEEM_PER_MINUTE=${PREDICTA_RATE_LIMIT_PASS_REDEEM_PER_MINUTE:-5}"
  "PREDICTA_RATE_LIMIT_PASS_REDEEM_PER_HOUR=${PREDICTA_RATE_LIMIT_PASS_REDEEM_PER_HOUR:-24}"
  "PREDICTA_RATE_LIMIT_ADMIN_PER_MINUTE=${PREDICTA_RATE_LIMIT_ADMIN_PER_MINUTE:-30}"
  "PREDICTA_RATE_LIMIT_ADMIN_PER_HOUR=${PREDICTA_RATE_LIMIT_ADMIN_PER_HOUR:-300}"
  "PREDICTA_RATE_LIMIT_BILLING_PER_MINUTE=${PREDICTA_RATE_LIMIT_BILLING_PER_MINUTE:-20}"
  "PREDICTA_RATE_LIMIT_BILLING_PER_HOUR=${PREDICTA_RATE_LIMIT_BILLING_PER_HOUR:-120}"
  "PREDICTA_RATE_LIMIT_AI_PER_MINUTE=${PREDICTA_RATE_LIMIT_AI_PER_MINUTE:-8}"
  "PREDICTA_RATE_LIMIT_AI_PER_HOUR=${PREDICTA_RATE_LIMIT_AI_PER_HOUR:-80}"
  "PREDICTA_AI_RESPONSE_CACHE_ENABLED=${PREDICTA_AI_RESPONSE_CACHE_ENABLED:-true}"
  "PREDICTA_AI_RESPONSE_CACHE_TTL_SECONDS=${PREDICTA_AI_RESPONSE_CACHE_TTL_SECONDS:-604800}"
  "PREDICTA_AI_RESPONSE_CACHE_MAX_ENTRIES=${PREDICTA_AI_RESPONSE_CACHE_MAX_ENTRIES:-500}"
  "PREDICTA_AI_MAX_CONTEXT_CHARS=${PREDICTA_AI_MAX_CONTEXT_CHARS:-14000}"
  "PREDICTA_AI_MAX_HISTORY_TURNS=${PREDICTA_AI_MAX_HISTORY_TURNS:-8}"
  "PREDICTA_AI_MAX_HISTORY_CHARS_PER_TURN=${PREDICTA_AI_MAX_HISTORY_CHARS_PER_TURN:-700}"
  "PREDICTA_OPENAI_TIMEOUT_SECONDS=${PREDICTA_OPENAI_TIMEOUT_SECONDS:-30}"
  "PREDICTA_GEMINI_TIMEOUT_SECONDS=${PREDICTA_GEMINI_TIMEOUT_SECONDS:-12}"
  "PREDICTA_KUNDLI_CACHE_ENABLED=${PREDICTA_KUNDLI_CACHE_ENABLED:-true}"
  "PREDICTA_KUNDLI_CACHE_TTL_SECONDS=${PREDICTA_KUNDLI_CACHE_TTL_SECONDS:-2592000}"
  "PREDICTA_KUNDLI_CACHE_MAX_ENTRIES=${PREDICTA_KUNDLI_CACHE_MAX_ENTRIES:-1000}"
  "PREDICTA_OBSERVABILITY_ENABLED=${PREDICTA_OBSERVABILITY_ENABLED:-true}"
  "PREDICTA_OBSERVABILITY_HASH_SALT=${PREDICTA_OBSERVABILITY_HASH_SALT:-}"
)

ENV_VARS_JOINED="$(IFS='|'; echo "${ENV_VARS[*]}")"

SECRET_VARS=(
  "PREDICTA_OPENAI_API_KEY=${PREDICTA_OPENAI_SECRET_NAME:-PREDICTA_OPENAI_API_KEY}:latest"
  "PREDICTA_GEMINI_API_KEY=${PREDICTA_GEMINI_SECRET_NAME:-PREDICTA_GEMINI_API_KEY}:latest"
)

SECRET_VARS_JOINED="$(IFS=','; echo "${SECRET_VARS[*]}")"

DEPLOY_ARGS=(
  run deploy "$SERVICE_NAME"
  --source "$REPO_ROOT/backend"
  --project "$PROJECT_ID"
  --region "$REGION"
  --allow-unauthenticated
  --ingress "$CLOUD_RUN_INGRESS"
  --max-instances "$CLOUD_RUN_MAX_INSTANCES"
  --concurrency "$CLOUD_RUN_CONCURRENCY"
  --set-env-vars "^|^$ENV_VARS_JOINED"
  --set-secrets "$SECRET_VARS_JOINED"
)

if [[ -n "${CLOUD_RUN_SERVICE_ACCOUNT:-}" ]]; then
  DEPLOY_ARGS+=(--service-account "$CLOUD_RUN_SERVICE_ACCOUNT")
fi

if [[ "${DRY_RUN:-false}" == "true" ]]; then
  printf 'gcloud'
  printf ' %q' "${DEPLOY_ARGS[@]}"
  printf '\n'
  exit 0
fi

gcloud "${DEPLOY_ARGS[@]}"
